const STORAGE_KEY='trackiu-mvp-v1';
const ROLE_LABELS={super_admin:'Super admin',manager:'Manager',trainer:'Coach',athlete:'Atleta'};
const ZONES={neck:'Cuello',shoulder:'Hombro',elbow:'Codo',wrist_hand:'Muñeca / mano',thoracic_back:'Espalda torácica',lumbar_back:'Espalda lumbar',hip_groin:'Cadera / ingle',knee:'Rodilla',ankle_foot:'Tobillo / pie'};
const patterns={squat:'Sentadilla',hinge:'Bisagra',horizontal_push:'Empuje horizontal',vertical_push:'Empuje vertical',horizontal_pull:'Tracción horizontal',vertical_pull:'Tracción vertical',carry:'Carga',locomotion:'Locomoción',jump:'Salto',rotation:'Rotación',core_bracing:'Core',cyclical:'Cíclico',mobility:'Movilidad'};
const exerciseSeed=[
 ['Back squat','squat',['knee','hip_groin','lumbar_back'],'high','Goblet squat'],['Front squat','squat',['knee','hip_groin'],'high','Box squat'],['Air squat','squat',['knee','hip_groin'],'medium','Box squat'],['Goblet squat','squat',['knee','hip_groin'],'medium','Box squat'],['Box squat','squat',['knee','hip_groin'],'low',null],['Deadlift','hinge',['lumbar_back','hip_groin'],'high','Kettlebell deadlift'],['Kettlebell deadlift','hinge',['lumbar_back','hip_groin'],'medium','Glute bridge'],['Glute bridge','hinge',['hip_groin'],'low',null],['Box jump','jump',['knee','ankle_foot'],'high','Box step-up'],['Box step-up','locomotion',['knee','ankle_foot'],'low',null],['Burpee','horizontal_push',['shoulder','wrist_hand','knee'],'high','Elevated burpee'],['Elevated burpee','horizontal_push',['shoulder','wrist_hand'],'medium','Bike'],['Push-up','horizontal_push',['shoulder','elbow','wrist_hand'],'medium','Incline push-up'],['Incline push-up','horizontal_push',['shoulder','elbow'],'low',null],['Strict press','vertical_push',['shoulder','elbow'],'high','Landmine press'],['Push press','vertical_push',['shoulder','elbow','lumbar_back'],'high','Landmine press'],['Landmine press','vertical_push',['shoulder'],'low',null],['Pull-up','vertical_pull',['shoulder','elbow'],'high','Ring row'],['Ring row','horizontal_pull',['shoulder','elbow'],'medium','Band row'],['Band row','horizontal_pull',['shoulder','elbow'],'low',null],['Toes-to-bar','core_bracing',['shoulder','lumbar_back','hip_groin'],'high','Dead bug'],['Dead bug','core_bracing',['lumbar_back'],'low',null],['Running','cyclical',['knee','ankle_foot'],'high','Bike'],['Row erg','cyclical',['lumbar_back','knee'],'medium','Bike'],['Bike','cyclical',['knee'],'low',null],['Double-under','jump',['ankle_foot','knee'],'high','Single-under'],['Single-under','jump',['ankle_foot'],'medium','Bike'],['Farmer carry','carry',['wrist_hand','shoulder'],'medium','Sled drag'],['Sled drag','locomotion',['knee','hip_groin'],'medium','Bike'],['Wall ball','squat',['knee','shoulder'],'high','Light goblet squat']
];
function uid(prefix){return prefix+'_'+Math.random().toString(36).slice(2,9)}
function freshState(){
 const exercises=exerciseSeed.map((e,i)=>({id:'ex'+(i+1),name:e[0],pattern:e[1],zones:e[2],exposure:e[3],alternative:e[4],active:true}));
 return {role:'super_admin',currentGym:'gym_a',currentAthlete:'ath_1',gyms:[{id:'gym_a',name:'Avenidas Box',city:'Madrid'},{id:'gym_b',name:'North Performance',city:'Bilbao'}],users:[
 {id:'u_admin',name:'Jose',email:'admin@trackiu.demo',roles:['super_admin']},{id:'u_manager',name:'Ana Martín',email:'ana@trackiu.demo',roles:['manager'],gymId:'gym_a'},{id:'u_coach',name:'Diego Ramos',email:'diego@trackiu.demo',roles:['trainer'],gymId:'gym_a'},
 {id:'ath_1',name:'Lucía Vega',email:'lucia@trackiu.demo',roles:['athlete'],gymId:'gym_a',grant:true},{id:'ath_2',name:'Marco Gil',email:'marco@trackiu.demo',roles:['athlete'],gymId:'gym_a',grant:true},{id:'ath_3',name:'Sara León',email:'sara@trackiu.demo',roles:['athlete'],gymId:'gym_a',grant:false},
 {id:'b_coach',name:'Nora Pérez',email:'nora@trackiu.demo',roles:['trainer'],gymId:'gym_b'},{id:'b_ath_1',name:'Iker Ruiz',email:'iker@trackiu.demo',roles:['athlete'],gymId:'gym_b',grant:true}],
 injuries:[{id:'inj_1',athleteId:'ath_1',zone:'knee',side:'right',severity:6,status:'active',note:'Molestia al aterrizar',updatedAt:new Date().toISOString()},{id:'inj_2',athleteId:'ath_2',zone:'shoulder',side:'left',severity:4,status:'active',note:'Molestia en overhead',updatedAt:new Date().toISOString()}],
 exercises,trainings:[{id:'tr_1',gymId:'gym_a',name:'Clase demo · Engine + legs',date:new Date().toISOString().slice(0,10),items:[{exerciseId:'ex1',dose:'5 × 5 · moderado'},{exerciseId:'ex9',dose:'4 × 8'},{exerciseId:'ex15',dose:'4 × 6'},{exerciseId:'ex24',dose:'10 min'}],participants:['ath_1','ath_2','ath_3'],status:'draft'}],
 preCheckins:{ath_1:{recovery:3,persistence:true,zone:'knee'},ath_2:{recovery:4,persistence:true,zone:'shoulder'}},decisions:{},feedback:{},interests:{programming:0,tracks:0},audit:[]};
}
let state=loadState();let currentView=location.hash.slice(1)||'inicio';
function loadState(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||freshState()}catch{return freshState()}}
function save(message='Guardado'){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));const el=document.querySelector('#save-state');if(el){el.textContent=message;setTimeout(()=>el.textContent='Guardado local',1200)}}
function role(){return state.role}
function gym(){return state.gyms.find(g=>g.id===state.currentGym)||state.gyms[0]}
function athletes(gymId=state.currentGym){return state.users.filter(u=>u.roles.includes('athlete')&&u.gymId===gymId)}
function athlete(){return state.users.find(u=>u.id===state.currentAthlete)||athletes()[0]}
function ex(id){return state.exercises.find(x=>x.id===id)}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function toast(msg){const t=document.querySelector('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),2600)}
const navByRole={super_admin:[['inicio','Inicio'],['gyms','Gimnasios'],['catalogo','Catálogo'],['intereses','Intereses']],manager:[['inicio','Inicio'],['equipo','Usuarios del gym'],['catalogo','Catálogo'],['programacion','Programación','Próximamente']],trainer:[['inicio','Inicio'],['atletas','Atletas'],['entrenamientos','Entrenamientos'],['cockpit','Cockpit'],['catalogo','Catálogo'],['programacion','Programación','Próximamente']],athlete:[['inicio','Inicio'],['perfil','Mi perfil'],['pre','Pre-check-in'],['sesion','Mi sesión'],['feedback','Feedback'],['tracks','Tracks','En investigación']]};
function buildNav(){const nav=document.querySelector('#primary-nav');nav.innerHTML=navByRole[role()].map(([id,label,status])=>`<a class="nav-link ${currentView===id?'active':''}" href="#${id}"><span>${label}</span>${status?`<span class="nav-status">${status}</span>`:''}</a>`).join('')}
function setChrome(title){document.querySelector('#page-title').textContent=title;document.querySelector('#role-badge').textContent=ROLE_LABELS[role()];document.querySelector('#context-label').textContent=role()==='super_admin'?'Plataforma':gym().name}
function render(){const allowed=navByRole[role()].map(n=>n[0]);if(!allowed.includes(currentView))currentView='inicio';buildNav();const renderer=views[currentView]||views.inicio;document.querySelector('#view').innerHTML=renderer();bindView();document.querySelector('.sidebar').classList.remove('open')}
function home(){setChrome('Inicio');const a=athletes();const openInj=state.injuries.filter(i=>i.status==='active'&&a.some(x=>x.id===i.athleteId)).length;const tr=state.trainings.filter(t=>t.gymId===state.currentGym).length;
 if(role()==='athlete'){const me=athlete();const injuryCount=state.injuries.filter(i=>i.athleteId===me.id&&i.status==='active').length;return `<div class="view-stack"><section class="hero"><div class="hero-main"><p class="eyebrow">Tu contexto, una decisión útil</p><h2>Entrena hoy con una sesión revisada para ti.</h2><p>Comparte cómo llegas, consulta la decisión de tu coach y responde después. TrackIU no diagnostica ni sustituye al profesional.</p><div class="inline"><a class="button" href="#pre">Completar pre-check-in</a><a class="button secondary" href="#sesion">Ver mi sesión</a></div></div><aside class="hero-side"><div><p class="eyebrow">Estado</p><h3>${esc(me.name)}</h3></div><div class="stack"><span class="badge ${me.grant?'':'warning'}">${me.grant?'Acceso concedido al gym':'Grant pendiente'}</span><span class="badge ${injuryCount?'warning':'neutral'}">${injuryCount} molestias activas</span></div></aside></section>${athleteSelectors()}${featureDoor('tracks')}</div>`}
 return `<div class="view-stack"><section class="hero"><div class="hero-main"><p class="eyebrow">MVP de decisión asistida</p><h2>Menos memoria. Más contexto antes de la clase.</h2><p>TrackIU cruza el entrenamiento con las restricciones del atleta, propone cambios explicables y mantiene la decisión final en manos del coach.</p><div class="inline">${role()==='trainer'?'<a class="button" href="#cockpit">Abrir cockpit</a>':role()==='manager'?'<a class="button" href="#equipo">Gestionar usuarios</a>':'<a class="button" href="#gyms">Gestionar gimnasios</a>'}<a class="button secondary" href="#catalogo">Explorar catálogo</a></div></div><aside class="hero-side"><div><p class="eyebrow">Ciclo validado</p><h3>Una decisión asistida completa</h3></div><div class="loop"><div class="loop-step"><span class="loop-number">1</span><span>Contexto y entrenamiento estructurado</span></div><div class="loop-step"><span class="loop-number">2</span><span>Filtro y propuesta explicable</span></div><div class="loop-step"><span class="loop-number">3</span><span>Coach decide; atleta responde</span></div></div></aside></section><section class="kpi-grid"><article class="kpi"><strong>${state.gyms.length}</strong><span>Gimnasios aislados</span></article><article class="kpi"><strong>${a.length}/3</strong><span>Atletas en ${esc(gym().name)}</span></article><article class="kpi"><strong>${openInj}</strong><span>Restricciones activas</span></article><article class="kpi"><strong>${tr}</strong><span>Entrenamientos</span></article></section>${role()==='trainer'?coachQueue():role()==='super_admin'?platformSnapshot():managerSnapshot()}</div>`}
}
function platformSnapshot(){return `<section class="section-card"><header class="section-header"><div><p class="eyebrow">Plataforma</p><h2>Gimnasios activos</h2></div><a class="button secondary" href="#gyms">Gestionar</a></header><div class="section-body card-grid">${state.gyms.map(g=>`<article class="mini-card"><span class="badge">${athletes(g.id).length}/3 atletas</span><h3>${esc(g.name)}</h3><p>${esc(g.city)} · ${state.users.filter(u=>u.gymId===g.id&&!u.roles.includes('athlete')).length} miembros de staff</p></article>`).join('')}</div></section>`}
function managerSnapshot(){return `<section class="section-card"><header class="section-header"><div><p class="eyebrow">Cupo piloto</p><h2>${esc(gym().name)}</h2></div><span class="badge ${athletes().length>=3?'warning':''}">${athletes().length}/3 atletas</span></header><div class="section-body"><p class="muted">El staff no consume cupo. El cuarto atleta se rechaza de forma explícita, sin crear registros parciales.</p></div></section>`}
function coachQueue(){const t=state.trainings.find(t=>t.gymId===state.currentGym);return `<section class="section-card"><header class="section-header"><div><p class="eyebrow">Siguiente decisión</p><h2>${t?esc(t.name):'Sin entrenamiento'}</h2></div><a class="button" href="#cockpit">Revisar atletas</a></header><div class="section-body">${t?proposalList(t,false):'<div class="empty">Crea un entrenamiento para generar propuestas.</div>'}</div></section>`}
function gymsView(){setChrome('Gimnasios');return `<div class="view-stack"><section class="section-card"><header class="section-header"><div><p class="eyebrow">Multi-tenant</p><h2>${state.gyms.length} gimnasios</h2></div><button class="button" data-action="new-gym">Añadir gimnasio</button></header><div class="section-body card-grid">${state.gyms.map(g=>`<article class="mini-card"><div class="inline between"><span class="badge">${athletes(g.id).length}/3 atletas</span><button class="button ghost" data-action="select-gym" data-id="${g.id}">Abrir</button></div><h3>${esc(g.name)}</h3><p>${esc(g.city)}</p><p>${state.users.filter(u=>u.gymId===g.id).length} usuarios vinculados</p></article>`).join('')}</div></section><section class="notice">Esta demo separa los datos operativos por gimnasio. La autenticación real y el aislamiento de base de datos pertenecen a la implementación backend.</section></div>`}
function usersView(){setChrome('Usuarios del gym');const a=athletes();return `<div class="view-stack"><section class="section-card"><header class="section-header"><div><p class="eyebrow">${esc(gym().name)}</p><h2>Atletas y staff</h2></div><div class="inline"><span class="badge ${a.length>=3?'warning':''}">${a.length}/3 atletas</span><button class="button" data-action="invite-athlete">Invitar atleta</button></div></header><div class="data-table-wrap"><table class="data-table"><thead><tr><th>Usuario</th><th>Rol</th><th>Acceso</th><th>Estado</th></tr></thead><tbody>${state.users.filter(u=>u.gymId===state.currentGym).map(u=>`<tr><td><strong>${esc(u.name)}</strong><br><span class="muted">${esc(u.email)}</span></td><td>${u.roles.map(r=>`<span class="badge neutral">${ROLE_LABELS[r]}</span>`).join(' ')}</td><td>${u.roles.includes('athlete')?`<button class="button ghost" data-action="toggle-grant" data-id="${u.id}">${u.grant?'Revocar grant':'Conceder grant'}</button>`:'Por rol de staff'}</td><td><span class="badge ${u.grant===false?'warning':''}">${u.grant===false?'Sin grant':'Activo'}</span></td></tr>`).join('')}</tbody></table></div></section></div>`}
function athleteSelectors(){if(role()!=='athlete')return '';return `<section class="notice"><strong>Persona de demo:</strong> ${esc(athlete().name)}. Usa “Entrar como” para comprobar los permisos de cada rol.</section>`}
function athletesView(){setChrome('Atletas');return `<div class="view-stack"><section class="section-card"><header class="section-header"><div><p class="eyebrow">Acceso contextual</p><h2>Atletas de ${esc(gym().name)}</h2></div></header><div class="section-body card-grid">${athletes().map(a=>{const inj=state.injuries.filter(i=>i.athleteId===a.id&&i.status==='active');return `<article class="mini-card"><div class="inline between"><span class="badge ${a.grant?'':'warning'}">${a.grant?'Grant activo':'Sin acceso'}</span><span class="muted small">${inj.length} molestias</span></div><h3>${esc(a.name)}</h3><p>${a.grant?inj.map(i=>`${ZONES[i.zone]} ${i.side==='right'?'derecha':i.side==='left'?'izquierda':'bilateral'} · ${i.severity}/10`).join('<br>')||'Sin restricciones activas':'El coach no puede consultar datos de salud.'}</p><footer><button class="button secondary" data-action="inspect-athlete" data-id="${a.id}" ${a.grant?'':'disabled'}>Ver contexto</button></footer></article>`}).join('')}</div></section></div>`}
function profileView(){setChrome('Mi perfil');const me=athlete(),inj=state.injuries.filter(i=>i.athleteId===me.id);return `<div class="view-stack"><section class="split"><article class="section-card"><header class="section-header"><div><p class="eyebrow">Privacidad</p><h2>Acceso del gimnasio</h2></div><span class="badge ${me.grant?'':'warning'}">${me.grant?'Concedido':'Revocado'}</span></header><div class="section-body stack"><p class="muted">Tus lesiones, cuestionarios y feedback te pertenecen. El gimnasio recibe acceso mediante un permiso explícito y revocable.</p><button class="button ${me.grant?'danger':''}" data-action="self-grant">${me.grant?'Revocar acceso':'Conceder acceso'}</button></div></article><article class="section-card"><header class="section-header"><div><p class="eyebrow">Contexto persistente</p><h2>Lesiones y molestias</h2></div><button class="button" data-action="new-injury">Añadir</button></header><div class="section-body status-list">${inj.length?inj.map(i=>`<div class="status-row"><span class="status-dot ${i.status==='active'?'amber':'green'}"></span><div><strong>${ZONES[i.zone]}</strong><p>${i.side} · intensidad ${i.severity}/10 · ${esc(i.note)}</p></div><button class="button ghost" data-action="resolve-injury" data-id="${i.id}">${i.status==='active'?'Resolver':'Reabrir'}</button></div>`).join(''):'<div class="empty">No has añadido molestias.</div>'}</div></article></section>${featureDoor('tracks')}</div>`}
function catalogView(){setChrome('Catálogo');return `<div class="view-stack"><section class="section-card"><header class="section-header"><div><p class="eyebrow">Taxonomía global</p><h2>${state.exercises.filter(e=>e.active).length} ejercicios activos</h2></div><input id="catalog-search" type="search" placeholder="Buscar ejercicio o zona" aria-label="Buscar en catálogo"></header><div class="data-table-wrap"><table class="data-table" id="catalog-table"><thead><tr><th>Ejercicio</th><th>Patrón</th><th>Zonas</th><th>Exposición</th><th>Alternativa</th></tr></thead><tbody>${state.exercises.map(e=>`<tr data-search="${esc((e.name+' '+patterns[e.pattern]+' '+e.zones.map(z=>ZONES[z]).join(' ')).toLowerCase())}"><td><strong>${esc(e.name)}</strong></td><td>${patterns[e.pattern]}</td><td>${e.zones.map(z=>`<span class="badge neutral">${ZONES[z]}</span>`).join(' ')}</td><td><span class="badge ${e.exposure==='high'?'danger':e.exposure==='medium'?'warning':''}">${e.exposure}</span></td><td>${e.alternative?esc(e.alternative):'<span class="muted">Revisión del coach</span>'}</td></tr>`).join('')}</tbody></table></div></section></div>`}
function trainingsView(){setChrome('Entrenamientos');const trs=state.trainings.filter(t=>t.gymId===state.currentGym);return `<div class="view-stack"><section class="section-card"><header class="section-header"><div><p class="eyebrow">Desde catálogo</p><h2>Entrenamientos</h2></div><button class="button" data-action="new-training">Crear entrenamiento</button></header><div class="section-body card-grid">${trs.map(t=>`<article class="mini-card"><div class="inline between"><span class="badge">${esc(t.date)}</span><span class="badge neutral">${t.participants.length} atletas</span></div><h3>${esc(t.name)}</h3><p>${t.items.map(i=>`${ex(i.exerciseId).name}: ${esc(i.dose)}`).join('<br>')}</p><footer><button class="button" data-action="open-cockpit" data-id="${t.id}">Pasar filtro</button><button class="button ghost" data-action="add-exercise" data-id="${t.id}">Añadir ejercicio</button></footer></article>`).join('')||'<div class="empty">Crea el primer entrenamiento desde el catálogo.</div>'}</div></section>${featureDoor('programming')}</div>`}
function proposalFor(t,a){if(!a.grant)return {status:'gray',summary:'Sin datos: grant no concedido',changes:[]};const restrictions=state.injuries.filter(i=>i.athleteId===a.id&&i.status==='active');const pre=state.preCheckins[a.id];let changes=[];for(const item of t.items){const e=ex(item.exerciseId);const conflict=restrictions.find(i=>e.zones.includes(i.zone)&&(e.exposure==='medium'||e.exposure==='high'));if(conflict){const alt=state.exercises.find(x=>x.name===e.alternative);changes.push({original:e.name,dose:item.dose,replacement:alt?.name||'Revisión del coach',reason:`${ZONES[conflict.zone]} · exposición ${e.exposure}`,rule:'zone_exposure_v1'});}}
 if(pre?.recovery<=2&&!changes.length)changes.push({original:'Densidad global',dose:'Programada',replacement:'Reducir densidad 15%',reason:'Recuperación baja declarada',rule:'recovery_v1'});return {status:changes.length?'amber':'green',summary:changes.length?`${changes.length} cambio${changes.length>1?'s':''} propuesto${changes.length>1?'s':''}`:'Mantener sesión',changes}}
function proposalList(t,actions=true){return `<div class="status-list">${t.participants.map(id=>{const a=state.users.find(u=>u.id===id),p=proposalFor(t,a),decision=state.decisions[t.id+'_'+id];return `<div class="status-row"><span class="status-dot ${p.status}"></span><div><strong>${esc(a.name)}</strong><p>${p.summary}${decision?' · decisión: '+decision:''}</p></div>${actions?`<button class="button secondary" data-action="review-proposal" data-training="${t.id}" data-athlete="${a.id}">Revisar</button>`:`<span class="badge ${p.status==='amber'?'warning':p.status==='gray'?'neutral':''}">${p.status}</span>`}</div>`}).join('')}</div>`}
function cockpitView(){setChrome('Cockpit');const t=state.trainings.find(t=>t.gymId===state.currentGym);if(!t)return `<div class="empty">No hay entrenamiento para revisar. <a class="button" href="#entrenamientos">Crear entrenamiento</a></div>`;return `<div class="view-stack"><section class="section-card"><header class="section-header"><div><p class="eyebrow">${esc(t.date)} · ${t.participants.length} atletas</p><h2>${esc(t.name)}</h2></div><span class="badge info">Reglas deterministas v1</span></header><div class="section-body">${proposalList(t,true)}</div></section><section class="notice warning">Las propuestas no diagnostican ni sustituyen el criterio profesional. El coach acepta, modifica, descarta o escala.</section></div>`}
function preView(){setChrome('Pre-check-in');const me=athlete(),existing=state.preCheckins[me.id]||{};return `<div class="view-stack"><section class="section-card"><header class="section-header"><div><p class="eyebrow">Solo lo que cambia la decisión</p><h2>¿Cómo llegas hoy?</h2></div><span class="badge">3 preguntas</span></header><form id="pre-form" class="section-body form-grid"><fieldset class="form-field full"><legend>Recuperación general</legend><div class="choice-row">${[1,2,3,4,5].map(n=>`<span class="choice"><input type="radio" id="rec${n}" name="recovery" value="${n}" ${existing.recovery==n?'checked':''} required><label for="rec${n}">${n}</label></span>`).join('')}</div><small>1 = muy baja · 5 = muy buena</small></fieldset><div class="form-field"><label for="pre-zone">Zona relevante hoy</label><select id="pre-zone" name="zone"><option value="">Ninguna</option>${Object.entries(ZONES).map(([k,v])=>`<option value="${k}" ${existing.zone===k?'selected':''}>${v}</option>`).join('')}</select></div><div class="form-field"><label for="persistence">¿La molestia persiste?</label><select id="persistence" name="persistence"><option value="false">No</option><option value="true" ${existing.persistence?'selected':''}>Sí</option></select></div><div class="form-field full"><button class="button" type="submit">Guardar check-in</button></div></form></section></div>`}
function sessionView(){setChrome('Mi sesión');const me=athlete(),t=state.trainings.find(t=>t.gymId===me.gymId),p=t?proposalFor(t,me):null,decision=t&&state.decisions[t.id+'_'+me.id];if(!t)return '<div class="empty">Tu coach todavía no ha publicado una sesión.</div>';const published=decision||'accepted';return `<div class="view-stack"><section class="section-card"><header class="section-header"><div><p class="eyebrow">Sesión final · ${esc(t.date)}</p><h2>${esc(t.name)}</h2></div><span class="badge">Revisada por coach</span></header><div class="section-body stack">${t.items.map(item=>{const e=ex(item.exerciseId),change=p.changes.find(c=>c.original===e.name);return `<article class="proposal"><div><span class="eyebrow">Original</span><h3>${esc(e.name)}</h3><p class="muted">${esc(item.dose)}</p></div><div class="arrow">→</div><div><span class="eyebrow">Para ti</span><h3>${change&&published!=='discarded'?esc(change.replacement):esc(e.name)}</h3><p class="muted">${change&&published!=='discarded'?esc(change.reason):'Sin cambios'}</p></div></article>`}).join('')}</div></section><a class="button" href="#feedback">Dar feedback al terminar</a></div>`}
function feedbackView(){setChrome('Feedback');const me=athlete(),done=state.feedback[me.id];if(done)return `<section class="section-card"><div class="empty"><span class="badge">Enviado</span><h2>Feedback registrado</h2><p>RPE ${done.rpe}/10 · fatiga ${done.fatigue}/10. La respuesta es inmutable y podrá condicionar la siguiente pregunta, sin crear una lesión automáticamente.</p></div></section>`;return `<section class="section-card"><header class="section-header"><div><p class="eyebrow">Después de entrenar</p><h2>¿Cómo fue la sesión?</h2></div></header><form id="feedback-form" class="section-body form-grid"><div class="form-field"><label for="rpe">RPE (1–10)</label><input id="rpe" name="rpe" type="number" min="1" max="10" required></div><div class="form-field"><label for="fatigue">Fatiga (1–10)</label><input id="fatigue" name="fatigue" type="number" min="1" max="10" required></div><div class="form-field"><label for="feedback-zone">¿Alguna molestia?</label><select id="feedback-zone" name="zone"><option value="">No</option>${Object.entries(ZONES).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></div><div class="form-field"><label for="side">Lado</label><select id="side" name="side"><option value="not_applicable">No aplica</option><option value="left">Izquierdo</option><option value="right">Derecho</option><option value="both">Ambos</option></select></div><div class="form-field full"><label for="note">Nota opcional</label><textarea id="note" name="note" placeholder="Describe solo lo necesario"></textarea></div><div class="form-field full"><button class="button" type="submit">Enviar feedback</button></div></form></section>`}
function featureDoor(type){const isTracks=type==='tracks',count=state.interests[type]||0;return `<section class="feature-door"><div><p class="eyebrow">${isTracks?'En investigación':'Próximamente'}</p><h2>${isTracks?'Tracks':'Programación'}</h2><p>${isTracks?'Un recorrido de 90 días con hitos de constancia, feedback y progreso. No premia entrenar con dolor ni obliga a mantener rachas.':'Diseña una temporada por objetivos, fases y semanas. TrackIU preparará borradores, señalará exposición repetida y dejará la publicación en manos del coach.'}</p></div><button class="button secondary" data-action="interest" data-feature="${type}">${count?'Interés registrado':'Sí, me gustaría'}</button></section>`}
function programmingView(){setChrome('Programación');return `<div class="view-stack">${featureDoor('programming')}<section class="notice">Esto es una puerta de descubrimiento honesta: registra interés, pero no simula una funcionalidad que aún no existe.</section></div>`}
function tracksView(){setChrome('Tracks');return `<div class="view-stack">${featureDoor('tracks')}<section class="notice">Tu clic sirve para priorizar entrevistas y validar el problema antes de construir el producto completo.</section></div>`}
function interestsView(){setChrome('Intereses');return `<div class="view-stack"><section class="kpi-grid"><article class="kpi"><strong>${state.interests.programming||0}</strong><span>Interés en Programación</span></article><article class="kpi"><strong>${state.interests.tracks||0}</strong><span>Interés en Tracks</span></article></section><section class="section-card"><header class="section-header"><h2>Eventos de descubrimiento</h2></header><div class="section-body"><p class="muted">En producción se persistirán user, feature, gym opcional, fuente, primer/último clic y contador. Esta demo almacena los clics solamente en este navegador.</p></div></section></div>`}
const views={inicio:home,gyms:gymsView,equipo:usersView,atletas:athletesView,perfil:profileView,catalogo:catalogView,entrenamientos:trainingsView,cockpit:cockpitView,pre:preView,sesion:sessionView,feedback:feedbackView,programacion:programmingView,tracks:tracksView,intereses:interestsView};
function modal(title,content,kicker='TrackIU MVP'){document.querySelector('#modal-title').textContent=title;document.querySelector('#modal-kicker').textContent=kicker;document.querySelector('#modal-content').innerHTML=content;document.querySelector('#modal').showModal()}
function bindView(){const search=document.querySelector('#catalog-search');if(search)search.addEventListener('input',()=>{document.querySelectorAll('#catalog-table tbody tr').forEach(r=>r.hidden=!r.dataset.search.includes(search.value.toLowerCase()))});const pre=document.querySelector('#pre-form');if(pre)pre.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(pre);state.preCheckins[athlete().id]={recovery:Number(f.get('recovery')),zone:f.get('zone'),persistence:f.get('persistence')==='true'};save();toast('Check-in guardado');location.hash='sesion'});const feedback=document.querySelector('#feedback-form');if(feedback)feedback.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(feedback);state.feedback[athlete().id]={rpe:Number(f.get('rpe')),fatigue:Number(f.get('fatigue')),zone:f.get('zone'),side:f.get('side'),note:f.get('note'),submittedAt:new Date().toISOString()};save();toast('Feedback registrado');render()})}
function handleAction(action,el){
 if(action==='select-gym'){state.currentGym=el.dataset.id;save('Gym seleccionado');render();return}
 if(action==='new-gym'){modal('Añadir gimnasio',`<form id="gym-form" class="stack"><div class="form-field"><label for="gym-name">Nombre</label><input id="gym-name" name="name" required></div><div class="form-field"><label for="gym-city">Ciudad</label><input id="gym-city" name="city" required></div><button class="button" type="submit">Crear gimnasio</button></form>`);setTimeout(()=>document.querySelector('#gym-form').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target),id=uid('gym');state.gyms.push({id,name:f.get('name'),city:f.get('city')});state.currentGym=id;save();document.querySelector('#modal').close();toast('Gimnasio creado');render()}));return}
 if(action==='invite-athlete'){if(athletes().length>=3){toast('Cupo completo: máximo 3 atletas activos');return}modal('Invitar atleta',`<form id="invite-form" class="stack"><div class="form-field"><label for="invite-name">Nombre</label><input id="invite-name" name="name" required></div><div class="form-field"><label for="invite-email">Email</label><input id="invite-email" name="email" type="email" required></div><button class="button" type="submit">Crear invitación</button></form>`);setTimeout(()=>document.querySelector('#invite-form').addEventListener('submit',e=>{e.preventDefault();if(athletes().length>=3)return;const f=new FormData(e.target),id=uid('ath');state.users.push({id,name:f.get('name'),email:f.get('email'),roles:['athlete'],gymId:state.currentGym,grant:false});save();document.querySelector('#modal').close();toast('Atleta invitado; grant pendiente');render()}));return}
 if(action==='toggle-grant'){const u=state.users.find(x=>x.id===el.dataset.id);u.grant=!u.grant;save();toast(u.grant?'Acceso concedido':'Acceso revocado');render();return}
 if(action==='self-grant'){const u=athlete();u.grant=!u.grant;save();toast(u.grant?'Acceso concedido':'Acceso revocado inmediatamente');render();return}
 if(action==='new-injury'){modal('Añadir lesión o molestia',`<form id="injury-form" class="form-grid"><div class="form-field"><label for="inj-zone">Zona corporal</label><select id="inj-zone" name="zone" required>${Object.entries(ZONES).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></div><div class="form-field"><label for="inj-side">Lado</label><select id="inj-side" name="side"><option value="left">Izquierdo</option><option value="right">Derecho</option><option value="both">Ambos</option><option value="not_applicable">No aplica</option></select></div><div class="form-field"><label for="severity">Intensidad 1–10</label><input id="severity" name="severity" type="number" min="1" max="10" value="4" required></div><div class="form-field full"><label for="inj-note">Nota</label><textarea id="inj-note" name="note"></textarea></div><div class="form-field full"><button class="button" type="submit">Guardar molestia</button></div></form>`);setTimeout(()=>document.querySelector('#injury-form').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);state.injuries.push({id:uid('inj'),athleteId:athlete().id,zone:f.get('zone'),side:f.get('side'),severity:Number(f.get('severity')),status:'active',note:f.get('note'),updatedAt:new Date().toISOString()});save();document.querySelector('#modal').close();toast('Molestia añadida');render()}));return}
 if(action==='resolve-injury'){const i=state.injuries.find(x=>x.id===el.dataset.id);i.status=i.status==='active'?'resolved':'active';i.updatedAt=new Date().toISOString();save();render();return}
 if(action==='inspect-athlete'){const a=state.users.find(x=>x.id===el.dataset.id),inj=state.injuries.filter(i=>i.athleteId===a.id&&i.status==='active');modal(a.name,`<div class="stack"><span class="badge">Grant activo</span>${inj.map(i=>`<div class="status-row"><span class="status-dot amber"></span><div><strong>${ZONES[i.zone]}</strong><p>${i.side} · ${i.severity}/10 · ${esc(i.note)}</p></div></div>`).join('')||'<p>Sin restricciones activas.</p>'}<p class="notice">Vista derivada mínima: el coach no necesita acceder a todas las respuestas crudas.</p></div>`,'Contexto del atleta');return}
 if(action==='new-training'){modal('Crear entrenamiento',`<form id="training-form" class="stack"><div class="form-field"><label for="training-name">Nombre de la clase</label><input id="training-name" name="name" required></div><div class="form-field"><label for="training-date">Fecha</label><input id="training-date" name="date" type="date" value="${new Date().toISOString().slice(0,10)}" required></div><button class="button" type="submit">Crear borrador</button></form>`);setTimeout(()=>document.querySelector('#training-form').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);state.trainings.push({id:uid('tr'),gymId:state.currentGym,name:f.get('name'),date:f.get('date'),items:[],participants:athletes().map(a=>a.id),status:'draft'});save();document.querySelector('#modal').close();toast('Entrenamiento creado');render()}));return}
 if(action==='add-exercise'){const t=state.trainings.find(x=>x.id===el.dataset.id);modal('Añadir ejercicio',`<form id="exercise-form" class="stack"><div class="form-field"><label for="exercise">Ejercicio de catálogo</label><select id="exercise" name="exerciseId">${state.exercises.filter(e=>e.active).map(e=>`<option value="${e.id}">${esc(e.name)} · ${e.exposure}</option>`).join('')}</select></div><div class="form-field"><label for="dose">Dosis</label><input id="dose" name="dose" placeholder="Ej. 4 × 8, moderado" required></div><button class="button" type="submit">Añadir al entrenamiento</button></form>`);setTimeout(()=>document.querySelector('#exercise-form').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);t.items.push({exerciseId:f.get('exerciseId'),dose:f.get('dose')});save();document.querySelector('#modal').close();toast('Ejercicio añadido');render()}));return}
 if(action==='open-cockpit'){currentView='cockpit';location.hash='cockpit';render();return}
 if(action==='review-proposal'){const t=state.trainings.find(x=>x.id===el.dataset.training),a=state.users.find(x=>x.id===el.dataset.athlete),p=proposalFor(t,a);modal(`Decisión para ${a.name}`,`<div class="stack"><span class="badge ${p.status==='amber'?'warning':p.status==='gray'?'neutral':''}">${p.summary}</span>${p.changes.length?p.changes.map(c=>`<article class="proposal"><div><span class="eyebrow">Original</span><h3>${esc(c.original)}</h3><p>${esc(c.dose)}</p></div><div class="arrow">→</div><div><span class="eyebrow">Propuesta</span><h3>${esc(c.replacement)}</h3><p>${esc(c.reason)} · regla ${c.rule}</p></div></article>`).join(''):'<p class="notice">No se detectan conflictos con los datos disponibles.</p>'}<div class="inline"><button class="button" type="button" data-decision="accepted">Aceptar</button><button class="button secondary" type="button" data-decision="modified">Modificar</button><button class="button ghost" type="button" data-decision="discarded">Descartar</button><button class="button danger" type="button" data-decision="escalated">Escalar</button></div></div>`,'Propuesta explicable');setTimeout(()=>document.querySelectorAll('[data-decision]').forEach(b=>b.addEventListener('click',()=>{state.decisions[t.id+'_'+a.id]=b.dataset.decision;save();document.querySelector('#modal').close();toast('Decisión registrada');render()})));return}
 if(action==='interest'){const f=el.dataset.feature;state.interests[f]=(state.interests[f]||0)+1;save('Interés registrado');toast('Interés registrado. Gracias.');render();return}
}
document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(el)handleAction(el.dataset.action,el)});
document.querySelector('#role-switcher').value=state.role;document.querySelector('#role-switcher').addEventListener('change',e=>{state.role=e.target.value;if(state.role==='athlete'){state.currentGym='gym_a';state.currentAthlete='ath_1'}else state.currentGym='gym_a';currentView='inicio';location.hash='inicio';save('Rol cambiado');render()});
document.querySelector('#theme-toggle').addEventListener('click',()=>{document.documentElement.dataset.theme=document.documentElement.dataset.theme==='dark'?'light':'dark'});document.querySelector('#menu-toggle').addEventListener('click',()=>document.querySelector('.sidebar').classList.toggle('open'));document.querySelector('#reset-demo').addEventListener('click',()=>{if(confirm('¿Reiniciar todos los datos de esta demo?')){state=freshState();localStorage.removeItem(STORAGE_KEY);document.querySelector('#role-switcher').value=state.role;currentView='inicio';location.hash='inicio';render();toast('Demo reiniciada')}});window.addEventListener('hashchange',()=>{currentView=location.hash.slice(1)||'inicio';render()});
render();
