import test from 'node:test'; import assert from 'node:assert/strict';
import { createDemoState } from '../src/demo-data.mjs'; import { generateProposal,createDecision,finalSession } from '../src/decision-engine.mjs';
const state=createDemoState(); const args={workout:state.workout,athleteId:'lucia',permission:true,restrictions:state.restrictions,precheck:state.prechecks.lucia};
test('same input produces equivalent business output',()=>{const a=generateProposal(args),b=generateProposal(args);delete a.generatedAt;delete b.generatedAt;assert.deepEqual(a,b)});
test('missing permission is gray',()=>assert.equal(generateProposal({...args,permission:false}).signal,'gray'));
test('missing precheck is gray',()=>assert.equal(generateProposal({...args,precheck:null}).signal,'gray'));
test('conflict is amber with directed alternative',()=>{const p=generateProposal(args);assert.equal(p.signal,'amber');assert.ok(p.changes.some(c=>c.replacementExerciseId==='box-step-up'))});
test('escalation is red and stops alternatives',()=>{const p=generateProposal({...args,precheck:{...args.precheck,escalation:'chest_pain'}});assert.equal(p.signal,'red');assert.equal(p.changes.length,0)});
test('pending proposal is not a final session',()=>{const p=generateProposal(args);assert.equal(finalSession({workout:state.workout,proposal:p}).status,'proposal_pending')});
test('modified decision requires and publishes modifications',()=>{const p=generateProposal(args);const mod=[{itemId:'item-2',replacementExerciseId:'box-step-up',finalDose:'3 × 6',reason:'Ajuste del coach'}];const d=createDecision({proposal:p,action:'coach_modified',actorId:'diego',modifications:mod});const s=finalSession({workout:state.workout,proposal:p,decision:d});assert.equal(s.items.find(i=>i.itemId==='item-2').dose,'3 × 6');assert.equal(d.proposalSnapshot.id,p.id)});
